# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d710f9ab3c816f1190444407a60b72cf7e991f293d94a0d5539bef4dae05d62d6b05aa83dbc28e069475f4b79211061478d63ba76214443bc0d33f21cceddba0

test:
  secret_key_base: a49a94f2de57760b76d9bede28c605c624e6c6b93e45e8161750374456aa11cfcdce4360505411e3a9cad6beefbc87f4c7a04e5efbf1d728e4eb8d50936dcfcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
